name: TechKey Analysis CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-qt pytest-flask
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=src --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Check code formatting with black
      run: |
        black --check src/ gui/ web/ tests/
    
    - name: Check import sorting with isort
      run: |
        isort --check-only src/ gui/ web/ tests/
    
    - name: Lint with flake8
      run: |
        flake8 src/ gui/ web/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ gui/ web/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t techkey-analysis .
    
    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 --name techkey-test techkey-analysis
        sleep 10
    
    - name: Check container status
      run: |
        docker ps -a
        docker logs techkey-test
    
    - name: Stop container
      run: |
        docker stop techkey-test
        docker rm techkey-test

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security scan
      uses: sast-scan/ci-scan@v2
      with:
        type: 'python'