version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://techkey:password@db:5432/techkey_analysis
      - SECRET_KEY=your-production-secret-key
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=techkey_analysis
      - POSTGRES_USER=techkey
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://techkey:password@db:5432/techkey_analysis
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  postgres_data: